<?php echo $header; ?>
<main class="phone-fill-end">
<div class="container">
	<h1>Önkéntes Nyugdíjpénztár</h1>
	<h2>Köszönjük! Adatait rögzítettük.</h2>
	<h3>Az Ön azonosítószáma: <span>323248674</span><a class="help" href="#">Segítséget kérek</a></h3>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus aliquid aliquam a qui, illo consectetur sed eveniet velit placeat, similique. Eius sequi nam totam optio maiores, ea facere cum sint?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat sapiente, veniam fugiat molestiae accusamus, dolores praesentium officia. Dolore eius explicabo omnis optio commodi tempore atque nemo, ipsa, alias, suscipit esse!</p>	
</div>
</main>
<?php echo $footer; ?>