<?php echo $header; ?>
<main class="phone-fill">
<div class="container">
	<h1>Önkéntes Nyugdíjpénztár</h1>
	<h2>Adja meg az alábbi adatokat, hogy kollégánk felkereshesse Önt és segítsen a nyomtatvány kitöltésében!</h2>
	<ul class="navigation phone">
		<li><a class="active" href="#"><span>1</span></a></li>
		<li><a href="#"><span>2</span></a></li>
	</ul>
	<div class="form-title-blue">Adatok</div>
	<form action="/aegon/telefonos-kitoltes/lepes-vege">
		<div class="form-box first">
			<div class="form-box-title">Személyes adatok</div>
			<div class="form-control">
				<div class="box">
					<label for="lastname">Vezetéknév: <span>*</span></label>
					<input id="lastname" type="text">
				</div>
				<div class="box">
					<label for="firstname">Keresztnév: <span>*</span></label>
					<input id="firstname" type="text">
				</div>
				<div class="box">
					<label for="birthday">Születési idő: <span>*</span></label>
					<input id="birthday" type="text">
				</div>
			</div>
		</div>
		<div class="form-box second">
			<div class="form-box-title">Elérhetőség</div>
			<div class="form-control">
				<div class="box">
					<label for="email">E-mail cím: <span>*</span></label>
					<input id="email" type="email">
				</div>
				<div class="box">
					<label for="email-ver">E-mail cím megerősítése: <span>*</span></label>
					<input id="email-ver" type="email">
				</div>
				<div class="box">
					<label for="phone">Telefon: <span>*</span></label>
					<input id="phone" type="text">
				</div>
			</div>
		</div>
		<div class="form-box third">
			<div class="form-box-title">Önkéntes Nyugdíjpénztár Információk</div>
			<div class="sub-title">Vállat havi tagdíj összesen:</div>
			<div class="prize-wrapper clear">
				<div class="prize-1" data-line="Ft/hó">
				</div>
			</div>
			<div class="sliders">
				<div id="slider-1">
				</div>
			</div>
			<div class="little-ones">
				<?php
					for( $i = 0; $i< 7 ;$i++){
						?>
						<div>							
						</div>
						<?php
					}
				 ?>
			</div>
			<div class="prizes">
				<div class="left">5000</div>
				<div class="center">25.000</div>
				<div class="right">45.000</div>
			</div>
			<div class="sub-title">Az összeg, amit havi kiegészítő nyugdíjszolgáltatásként kapni szeretnék majd:</div>
				<div class="prize-wrapper clear">
				<div class="prize-2" data-line="Ft/hó">
				</div>
			</div>
			<div class="sliders">
				<div id="slider-2">
				</div>
			</div>
						<div class="little-ones">
				<?php
					for( $i = 0; $i< 7 ;$i++){
						?>
						<div>							
						</div>
						<?php
					}
				 ?>
			</div>
			<div class="prizes">
				<div class="left">5000</div>
				<div class="center">25.000</div>
				<div class="right">45.000</div>
			</div>
			<div class="sub-title">Az összeg, amit adott idő alatt nyugdíjvagyonként összegyűjt a vállalt havi tagdíj mellett:</div>
				<div class="prize-wrapper clear">
				<div class="prize-3" data-line="Ft/hó">
				</div>
			</div>
			<div class="sliders">
				<div id="slider-3">
				</div>
			</div>
						<div class="little-ones">
				<?php
					for( $i = 0; $i< 7 ;$i++){
						?>
						<div></div>
						<?php
					}
				 ?>
			</div>
			<div class="prizes">
				<div class="left">5000</div>
				<div class="center">25.000</div>
				<div class="right">45.000</div>
			</div>
			<div class="checkbox margin-fix">
				<input type="checkbox" name="checkboxG1" id="checkboxG1" class="css-checkbox" />
				<label for="checkboxG1" class="css-label">Az adatkezelésről szóló tájékoztatás ismeretében hozzájárulok ahhoz, hogy az AEGON Magyarország Pénztárszolgáltató Zrt. (Pénztárszolgáltató) a jelen nyilatkozaton megadott személyes adataimat az önkéntes nyugdíjpénztári tagsági jogviszonyom létrehozása érdekében kezelje, ezzel kapcsolatban engem telefonon, illetve elektronikus úton megkeressen a regisztrációt
					követő 1 évig. <a href="#">Olvassa el a teljes tájékoztatást!</a></label>
				</div>
				<div class="checkbox">
					<input type="checkbox" name="checkboxG2" id="checkboxG2" class="css-checkbox" />
					<label for="checkboxG2" class="css-label">Az adatkezelésről szóló tájékoztatás ismeretében hozzájárulok ahhoz, hogy az AEGON Magyarország Pénztárszolgáltató Zrt. a jelen nyilatkozaton megadott személyes adataimat marketing- és üzletszerzési célból jelen hozzájáruló nyilatkozatom visszavonásáig kezelje, részemre postai, e-mail és más elektronikus úton reklámcélú üzeneteket küldjön.
						<a href="#">Olvassa el a teljes tájékoztatást!</a></label>
					</div>
				</div>
				<div class="form-box fourth">
					<div class="form-box-title">Elérhetőség</div>
					<div class="radio-buttons">
						<input type="radio" name="radiog_lite" id="radio1" class="css-checkbox" /><label for="radio1" class="css-label radGroup1">Most</label>
						<input type="radio" name="radiog_lite" id="radio2" class="css-checkbox" /><label for="radio2" class="css-label radGroup1">Délelőtt</label>
						<input type="radio" name="radiog_lite" id="radio3" class="css-checkbox" /><label for="radio3" class="css-label radGroup1">Délután</label>
						<input type="radio" name="radiog_lite" id="radio4" class="css-checkbox" /><label for="radio4" class="css-label radGroup1">Este</label>
					</div>
				</div>
				<input class="btn-blue" type="submit" value="Visszahívást kérek">
			</form>
		</div>
		</main>
		<?php echo $footer; ?>