<?php echo $header; ?>
<main class="phone-fill">
	<div class="container">
		<h1>Önkéntes Nyugdíjpénztár</h1>
		<h2>Adja meg az alábbi adatokat, hogy kollégánk felkereshesse Önt és segítsen a nyomtatvány kitöltésében!</h2>
		<ul class="navigation phone">
			<li><a class="active" href="#"><span>1</span></a></li>
			<li><a href="#"><span>2</span></a></li>
		</ul>
	</div>
</main>
<?php echo $footer; ?>