<?php echo $header; ?>
<main class="phone-fill-step2">
<div class="container">
	<h1>Önkéntes Nyugdíjpénztár</h1>
	<h2>Kérjük, az önkéntes nyugdíjpénztári belépéshez adja meg az alábbi adatokat.</h2>
	<ul class="navigation phone">
		<li><a href="#"><span>1</span></a></li>
		<li><a class="active" href="#"><span>2</span></a></li>
	</ul>
	<div class="form-title-blue">Ellenőrzés<a href="#" class="help">Segítséget kérek</a></div>
		<div class="form-box first">
			<div class="form-box-title">Személyes adatok</div>
			<div class="summary-wrapper clear">
				<div class="row">
					<div class="box">
						Vezetéknév:
						<span>Kovács</span>
					</div>
					<div class="box">
						Keresztnév:
						<span>József</span>
					</div>
					<div class="box">
						Születési idő:
						<span>1964. 05. 12.</span>
					</div>
				</div>
			</div>
		</div>
		<div class="form-box second">
			<div class="form-box-title">Elérhetőség</div>
			<div class="summary-wrapper clear">
				<div class="row">
					<div class="box">
						Mobiltelefon:
						<span>+36 20 1244 567</span>
					</div>
					<div class="box">
						E-mail:
						<span>tesz.tlaldlld@gmail.hu</span>
					</div>
					<div class="box">
						Elérhetőség:
						<span>Délelőtt</span>
					</div>
				</div>
			</div>
		</div>
		<div class="form-box third">
			<div class="form-box-title">Önkéntes Nyugdíjpénztár Információk</div>
			<div class="summary-wrapper clear">
				<div class="row">
					<div class="box">
						Online ügyintézés:
						<span>igen</span>
					</div>
					<div class="box">
						Átlépés esetén előző pénztár neve:
						<span>-</span>
					</div>
					<div class="box">
						Tagdíj fizető:
						<span>Magam fizetem</span>
					</div>
					<div class="box">
						Tagdíj összege:
						<span>Fix összeg</span>
					</div>
				</div>
				<div class="row">
					<div class="box">
						Vállalom az évenkénti tagdíj növekedést:
						<span>igen</span>
					</div>
					<div class="box">
						Menedzselt alap:
						<span>kiegyensúlyozott</span>
					</div>
					<div class="box">
						Vállalt havi tagdíj:
						<span>10 000 Ft</span>
					</div>
					<div class="box">
						Kedvezményezett:
						<span>-</span>
					</div>
				</div>
				<div class="row">
					<div class="box">
						Tagdíj fizetési módja:
						<span>banki utalás</span>
					</div>
					<div class="box">
						Tagdíj fizetés gyakorisága:
						<span>negyedéves</span>
					</div>
				</div>
			</div>
			<div class="checkbox">
				<input type="checkbox" name="checkboxG1" id="checkboxG1" class="css-checkbox" />
				<label for="checkboxG1" class="css-label">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad est ut aliquam facere reprehenderit doloremque, possimus, ea fugiat similique sequi, architecto eveniet pariatur quos quia? Quos, sequi autem dignissimos alias. <a href="#">Olvassa el a teljes tájékoztatást!</a>
				</label>
			</div>
			<div class="checkbox cant">
				<input type="checkbox" name="checkboxG2" id="checkboxG2" class="css-checkbox" />
				<label for="checkboxG2" class="css-label">
					Nem tudom kinyomtatni kérem, hogy a levelezési címemre postázzák ki.
				</label>
			</div>
		</div>
		<a href="/aegon/telefonos-kitoltes/lepes-1" class="btn-ghost">Vissza</a>
		<a class="btn-blue" href="/aegon/telefonos-kitoltes/lepes-vege">Következő</a>
</div>
</main>
<?php echo $footer; ?>