<?php echo $header; ?>
<main class="online-fill">
<div class="container">
	<h1>Önkéntes Nyugdíjpénztár</h1>
	<h2>Kérjük, az önkéntes nyugdíjpénztári belépéshez adja meg az alábbi adatokat.</h2>
	<ul class="navigation online">
		<li><a class="active" href="#"><span>1</span></a></li>
		<li><a href="#"><span>2</span></a></li>
		<li><a href="#"><span>3</span></a></li>
		<li><a href="#"><span>4</span></a></li>
		<li><a href="#"><span>5</span></a></li>
	</ul>
	<div class="form-title-blue">Adatok<a href="#" class="help">Segítséget kérek</a></div>
	<form action="/aegon/online-kitoltes/lepes-2">
		<div class="form-box first clear">
			<div class="form-box-title">Személyes adatok</div>
			<div class="form-control">
				<div class="box">
					<span>Neme:</span>
					<div class="radio-buttons">
						<input type="radio" name="radiog_lite" id="radio1" class="css-checkbox" /><label for="radio1" class="css-label radGroup1">Férfi</label>
						<input type="radio" name="radiog_lite" id="radio2" class="css-checkbox" /><label for="radio2" class="css-label radGroup1">Nő</label>
					</div>
				</div>
			</div>
			<div class="form-control">
				<div class="box">
					<label for="title">Titulus</label>
					<input id="title" type="text">
				</div>
			</div>
			<div class="form-control">
				<div class="box">
					<label for="lastname">Vezetéknév: <span>*</span></label>
					<input id="lastname" type="text">
				</div>
				<div class="box">
					<label for="firstname">Keresztnév: <span>*</span></label>
					<input id="firstname" type="text">
				</div>
			</div>
			<div class="form-control">
				<div class="box">
					<label for="birthplace">Születési hely:</label>
					<input id="birthplace" type="text">
				</div>
				<div class="box">
					<label for="birthday">Születési idő:</label>
					<input id="birthday" type="text">
				</div>
			</div>
			<div class="form-control">
				<div class="box">
					<label for="mother-name">Anyja születési neve <span>*</span></label>
					<input id="mother-name" type="text">
				</div>
			</div>
		</div>
		<div class="form-box second">
			<div class="form-box-title">Hivatalos adatok</div>
			<div class="form-control">
				<div class="box">
					<label for="nationality">Állampolgárság: <span>*</span></label>
					<input id="nationality" type="text">
				</div>
				<div class="box">
					<div class="info-popup">
						<a href="#"></a>
						<div class="popup">
							<h4>Azonosító okmány típusa:</h4>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate non inventore, ea nemo, suscipit laborum, similique illo rem quos itaque praesentium iusto beatae vitae excepturi, minus maxime qui ducimus eos!</p>
						</div>
					</div>
					<label for="id-doc-type">Azonosító okmány típusa: <span>*</span></label>
					<input id="id-doc-type" type="text">
				</div>
			</div>
			<div class="form-control">
				<div class="box">
					<label for="id-doc-number">Azonosító okmány száma: <span>*</span></label>
					<input id="id-doc-number" type="text">
				</div>
				<div class="box">
					<label for="tax-id-number">Adóazonosító jel: <span>*</span></label>
					<input id="tax-id-number" type="text">
				</div>
			</div>
		</div>
		<div class="form-box third">
			<div class="form-box-title">Önkéntes Nyugdíjpénztár Információk</div>
			<div class="sub-title first">Kérjük, állítsa be, hogy mennyit szeretne havonta megtakarítani:
			<div class="info-popup">
				<a href="#"></a>
				<div class="popup">
				<h4>Azonosító okmány típusa:</h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate non inventore, ea nemo, suscipit laborum, similique illo rem quos itaque praesentium iusto beatae vitae excepturi, minus maxime qui ducimus eos!</p>
				</div>
			</div>
			</div>
			<div class="prize-wrapper clear">
				<div class="prize-1" data-line="Ft/hó">
				</div>
			</div>
			<div class="sliders">
				<div id="slider-1">
				</div>
			</div>
			<div class="little-ones">
				<?php
					for( $i = 0; $i< 7 ;$i++){
				?>
				<div>
				</div>
				<?php
				}
				?>
			</div>
			<div class="prizes">
				<div class="left">5000</div>
				<div class="center">25.000</div>
				<div class="right">45.000</div>
			</div>
			<div class="sub-title second">Az összeg, amit havi kiegészítő nyugdíjszolgáltatásként kapni szeretnék majd:
			<div class="info-popup">
				<a href="#"></a>
				<div class="popup">
				<h4>Azonosító okmány típusa:</h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate non inventore, ea nemo, suscipit laborum, similique illo rem quos itaque praesentium iusto beatae vitae excepturi, minus maxime qui ducimus eos!</p>
				</div>
			</div>
			</div>
			<div class="prize-wrapper clear">
				<div class="prize-2" data-line="Ft/hó">
				</div>
			</div>
			<div class="sliders">
				<div id="slider-2">
				</div>
			</div>
			<div class="little-ones">
				<?php
					for( $i = 0; $i< 7 ;$i++){
				?>
				<div>
				</div>
				<?php
				}
				?>
			</div>
			<div class="prizes">
				<div class="left">5000</div>
				<div class="center">25.000</div>
				<div class="right">45.000</div>
			</div>
			<div class="sub-title third">Az összeg, amit adott idő alatt nyugdíjvagyonként összegyűjt a vállalt havi tagdíj mellett:
			<div class="info-popup">
				<a href="#"></a>
				<div class="popup">
				<h4>Azonosító okmány típusa:</h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate non inventore, ea nemo, suscipit laborum, similique illo rem quos itaque praesentium iusto beatae vitae excepturi, minus maxime qui ducimus eos!</p>
				</div>
			</div>
			</div>
			<div class="prize-wrapper clear">
				<div class="prize-3" data-line="Ft/hó">
				</div>
			</div>
			<div class="sliders">
				<div id="slider-3">
				</div>
			</div>
			<div class="little-ones">
				<?php
					for( $i = 0; $i< 7 ;$i++){
				?>
				<div></div>
				<?php
				}
				?>
			</div>
			<div class="prizes">
				<div class="left">5000</div>
				<div class="center">25.000</div>
				<div class="right">45.000</div>
			</div>
			</div>
			<input class="btn-blue" type="submit" value="Következő">
		</form>
</div>
</main>
<?php echo $footer; ?>