<?php echo $header; ?>
<main class="online-fill-step5">
<div class="container">
	<h1>Önkéntes Nyugdíjpénztár</h1>
	<h2>Kérjük, az önkéntes nyugdíjpénztári belépéshez adja meg az alábbi adatokat.</h2>
	<ul class="navigation online">
		<li><a href="#"><span>1</span></a></li>
		<li><a href="#"><span>2</span></a></li>
		<li><a href="#"><span>3</span></a></li>
		<li><a href="#"><span>4</span></a></li>
		<li><a class="active" href="#"><span>5</span></a></li>
	</ul>
	<div class="form-title-blue">Ellenőrzés<a href="#" class="help">Segítséget kérek</a></div>
	<form action="/aegon/online-lepes/lepes-vege">
		<div class="form-box first">
			<div class="form-box-title">Személyes adatok</div>
			<div class="summary-wrapper clear">
				<div class="row">
					<div class="box">
						Neme:
						<span>férfi</span>
					</div>
					<div class="box">
						Titulus:
						<span>özvegy</span>
					</div>
				</div>
				<div class="row">
					<div class="box">
						Vezetéknév:
						<span>Kovács</span>
					</div>
					<div class="box">
						Keresztnév:
						<span>József</span>
					</div>
					<div class="box">
						Születési vezetéknév:
						<span>-</span>
					</div>
					<div class="box">
						Születési keresztnév:
						<span>-</span>
					</div>
				</div>
				<div class="row">
					<div class="box">
						Születési hely:
						<span>Bükkszentkereszt</span>
					</div>
					<div class="box">
						Születési idő:
						<span>1964. 05. 12.</span>
					</div>
					<div class="box">
						Anyja születési neve:
						<span>Kiss Erzsébet</span>
					</div>
				</div>
			</div>
		</div>
		<div class="form-box second">
			<div class="form-box-title">Hivatalos adatok</div>
			<div class="summary-wrapper clear">
				<div class="row">
					<div class="box">
						Állampolgárság:
						<span>magyar</span>
					</div>
					<div class="box">
						Azonosító okmány típusa:
						<span>személyi igazolvány</span>
					</div>
					<div class="box">
						Azonosító okmány száma:
						<span>KHJSD34</span>
					</div>
					<div class="box">
						Adóazonosító jel:
						<span>342532637</span>
					</div>
				</div>
			</div>
		</div>
		<div class="form-box third">
			<div class="form-box-title">Lakcím / Elérhetőség</div>
			<div class="summary-wrapper clear">
				<div class="row">
					<div class="box">
						Ország:
						<span>Magyarország</span>
					</div>
					<div class="box">
						Irányítószám:
						<span>1123</span>
					</div>
					<div class="box">
						Város:
						<span>Budapest</span>
					</div>
					<div class="box">
						Utca/házszám:
						<span>Podmancizkkkss u. 12. szuterén 1. 66/44</span>
					</div>
				</div>
				<div class="row">
					<div class="box">
						Mobiltelefon:
						<span>+36 20 1244 567</span>
					</div>
					<div class="box">
						E-mail:
						<span>tesz.tlaldlld@sdasdads.hu</span>
					</div>
				</div>
			</div>
		</div>
		<div class="form-box fourth">
			<div class="form-box-title">Önkéntes Nyugdíjpénztár Információk</div>
			<div class="summary-wrapper clear">
				<div class="row">
					<div class="box">
						Online ügyintézés:
						<span>igen</span>
					</div>
					<div class="box">
						Átlépés esetén előző pénztár neve:
						<span>-</span>
					</div>
					<div class="box">
						Tagdíj fizető:
						<span>Magam fizetem</span>
					</div>
					<div class="box">
						Tagdíj összege:
						<span>Fix összeg</span>
					</div>
				</div>
				<div class="row">
					<div class="box">
						Vállalom az évenkénti tagdíj növekedést:
						<span>igen</span>
					</div>
					<div class="box">
						Menedzselt alap:
						<span>kiegyensúlyozott</span>
					</div>
					<div class="box">
						Vállalt havi tagdíj:
						<span>10 000 Ft</span>
					</div>
					<div class="box">
						Kedvezményezett:
						<span>-</span>
					</div>
				</div>
				<div class="row">
					<div class="box">
						Tagdíj fizetési módja:
						<span>banki utalás</span>
					</div>
					<div class="box">
						Tagdíj fizetés gyakorisága:
						<span>negyedéves</span>
					</div>
				</div>
			</div>
			<div class="checkbox">
				<input type="checkbox" name="checkboxG1" id="checkboxG1" class="css-checkbox" />
				<label for="checkboxG1" class="css-label">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad est ut aliquam facere reprehenderit doloremque, possimus, ea fugiat similique sequi, architecto eveniet pariatur quos quia? Quos, sequi autem dignissimos alias. <a href="#">Olvassa el a teljes tájékoztatást!</a></p>
				</label>
			</div>
			<div class="checkbox cant">
				<input type="checkbox" name="checkboxG2" id="checkboxG2" class="css-checkbox" />
				<label for="checkboxG2" class="css-label">
					Nem tudom kinyomtatni kérem, hogy a levelezési címemre postázzák ki.
				</label>
			</div>
		</div>
		<a href="/aegon/online-kitoltes/lepes-4" class="btn-ghost">Vissza</a>
		<input class="btn-blue" type="submit" value="Következő">
	</form>
</div>
</main>
<?php echo $footer; ?>