<?php echo $header; ?>
<main class="online-fill-step4">
<div class="container">
	<h1>Önkéntes Nyugdíjpénztár</h1>
	<h2>Kérjük, az önkéntes nyugdíjpénztári belépéshez adja meg az alábbi adatokat.</h2>
	<ul class="navigation online">
		<li><a href="#"><span>1</span></a></li>
		<li><a href="#"><span>2</span></a></li>
		<li><a href="#"><span>3</span></a></li>
		<li><a class="active" href="#"><span>4</span></a></li>
		<li><a href="#"><span>5</span></a></li>
	</ul>
	<div class="form-title-blue">Kedvezményezettek<a href="#" class="help">Segítséget kérek</a></div>
	<form action="/aegon/online-kitoltes/lepes-5">
		<div class="form-box first">
			<div class="form-box-title">Kedvezményezett adatai:</div>
			<div class="form-control">
				<div class="box">
					<label for="lastname">Vezetéknév: <span>*</span></label>
					<input id="lastname" type="text">
				</div>
				<div class="box">
					<label for="firstname">Keresztnév: <span>*</span></label>
					<input id="firstname" type="text">
				</div>
			</div>
			<div class="form-control">
				<div class="box">
					<label for="birthplace">Születési hely:</label>
					<input id="birthplace" type="text">
				</div>
				<div class="box">
					<label for="birthday">Születési idő:</label>
					<input id="birthday" type="text">
				</div>
			</div>
			<div class="form-control">
				<div class="box">
					<label for="mother-name">Anyja születési neve <span>*</span></label>
					<input id="mother-name" type="text">
				</div>
			</div>
			<div class="form-control">
				<div class="box">
					<label for="tax-sign">Adóazonosító jel</label>
					<input id="tax-sign" type="text">
				</div>
			</div>
		</div>
		<div class="form-box second">
			<div class="form-box-title">Levelezési cím:</div>
			<div class="form-control">
				<div class="box">
					<label for="country">Ország:</label>
					<input id="country" type="text">
				</div>
			</div>
			<div class="form-control">
				<div class="box">
					<label for="zipcode">Irányítószám:</label>
					<input id="zipcode" type="number">
					<span>Kazincbarcika</span>
				</div>
			</div>
			<div class="form-control">
				<div class="box">
					<label for="address">Cím:</label>
					<input id="address" type="text">
				</div>
				<div class="box">
					<label for="house-number">Házszám:</label>
					<input id="house-number" type="text">
				</div>
				<div class="box">
					<label for="floor">Emelet:</label>
					<input id="floor" type="text">
				</div>
				<div class="box">
					<label for="door">Ajtó:</label>
					<input id="door" type="text">
				</div>
			</div>
			<div class="form-control">
				<div class="box">
					<label for="beneficiaries-rate">Kedvezményezettségi mértéke:</label>
					<input id="beneficiaries-rate" type="nunber">
					<span>%</span>
				</div>
			</div>
		</div>
		<a href="/aegon/online-kitoltes/lepes-3.5" class="btn-ghost">Vissza</a>
		<input class="btn-blue" type="submit" value="Következő">
	</form>
</div>
</main>
<?php echo $footer; ?>